@startuml
class Pedido{
    - Long id
    - String status
    - LocalDateTime dataAbertura
    - LocalDateTime dataCancelado
    - LocalDateTime dataPronto
    - LocalDateTime dataEntregue
    - List listaItens
    - StatusPedido status
}

class ItemPedido{
    - Long id
    - Douvle vUnit
}

class Produto{
    - Long id
    - String name
    - String descricao
    - Double valor
    - String categoria
    - Double qtd
    - String imagem
}

@enduml